### ISSUE TITLE
Font validation - 'name' table usability

### ISSUE THREAD

**Issue by kcrouch** [atbrask/c64ttf#1]
Generated a couple of fonts where the "Creator" field contained a space.

On macOS 10.14.6, trying to install one of these fonts brought up a Font Validation window.

```
Problems may have been found with some font files during validation.

'name' table usability

1 minor problem was found. Proceed with caution
```

Setting the creator to something without a space generated a working font that installed fine without validation issues.

**Comment by atbrask** [comment]
Thanks for your interest in my project!

I have successfully reproduced the bug on macOS 10.13.6.

The 'name' table in the generated font file contains a PostScript name for the font. It turns out there are some pretty strict rules for which characters are allowed (e.g. no spaces) as well as a length limitation. I have put in some extra checks for this, and now macOS will happily install fonts even with spaces in the creator name.
